version: '3'
services:
    web:
        container_name: redis-auth
          restart: always
          build: ./authserver
          expose:
            - "8000"
          links:
            - redis:redis
          environment:
            DEBUG: 'true'

  redis:
    container_name: redis
    image: redis:5.0.7-alpine
    hostname: redis
    networks:
      - redis-net
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    restart: always

networks:
  redis-net:

volumes:
  redis-data: