version: '3.7'

services:

  rabbitmq-management:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15671:15671
      - 15672:15672
      - 5671:5671
      - 5672:5672
    restart: unless-stopped